<?php
/**
 * Implements hook_perm().
 */
function heartbeat_tab_perm() {
	return array(
		'view heartbeat tab',
	);
}

/**
 * Implements hook_preprocess_page().
 * 
 * Shows a tab on the frontpage for another page. Used to display a heartbeat newsfeed.
 * 
 * @param mixed
 */
function heartbeat_tab_preprocess_page(&$vars) {
	if(user_access('view heartbeat tab')) {
		$newsfeed_url = 'heartbeat/publicheartbeat';
		if(drupal_is_front_page() || $_GET['q'] == $newsfeed_url) {
			$attributes = array('class'=>'tabs primary');
			$links = array(
				'custom-tab-1' => array(
					'title' => t('Aktuelles', NULL, 'de'),
					'href' => '<front>',
				),
				'custom-tab-2' => array(
					'title' => t('Letzte Aktivitäten', NULL, 'de'),
					'href' => $newsfeed_url,
				),
			);
			$vars['tabs'] = theme_links($links, $attributes);
		}		
	}
}